<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hsudarshan-a01.vmware.com" failures="2" tests="18" name="com.sample.api.tests.PetsTests" time="48.014" errors="0" timestamp="2022-09-18T17:49:05 IST" skipped="0">
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="4.143"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.574"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.575"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="2.702"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.573"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="3.189"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.573"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.577">
    <failure message="created and actual pet are not matching expected [Pet(id=2187, category=PetsCategory(id=53045, name=hamster), name=Jeanette Akenja Nearing, photoUrls=[www.darin-olson.info, www.mack-jast.name], tags=null, status=Available)] but found [Pet(id=2187, category=PetsCategory(id=53045, name=hamster), name=Jeanette Akenja Nearing, photoUrls=[www.darin-olson.info, www.mack-jast.name], tags=[], status=Available)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: created and actual pet are not matching expected [Pet(id=2187, category=PetsCategory(id=53045, name=hamster), name=Jeanette Akenja Nearing, photoUrls=[www.darin-olson.info, www.mack-jast.name], tags=null, status=Available)] but found [Pet(id=2187, category=PetsCategory(id=53045, name=hamster), name=Jeanette Akenja Nearing, photoUrls=[www.darin-olson.info, www.mack-jast.name], tags=[], status=Available)]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at com.sample.api.assertions.PetsAPIAssertions.assertCreatePetResponse(PetsAPIAssertions.java:38)
at com.sample.api.tests.PetsTests.createPetsTest(PetsTests.java:152)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- createPetsTest -->
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="2.657"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="1.388"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="1.388"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.572"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.573"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="2.661"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.574"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.574"/>
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="createPetsTest" time="2.578">
    <failure message="created and actual pet are not matching expected [Pet(id=73699, category=PetsCategory(id=66448, name=trout), name=Oren Jellow, photoUrls=null, tags=[PetTag(id=89742, name=Blake Simonis)], status=Available)] but found [Pet(id=73699, category=PetsCategory(id=66448, name=trout), name=Oren Jellow, photoUrls=[], tags=[PetTag(id=89742, name=Blake Simonis)], status=Available)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: created and actual pet are not matching expected [Pet(id=73699, category=PetsCategory(id=66448, name=trout), name=Oren Jellow, photoUrls=null, tags=[PetTag(id=89742, name=Blake Simonis)], status=Available)] but found [Pet(id=73699, category=PetsCategory(id=66448, name=trout), name=Oren Jellow, photoUrls=[], tags=[PetTag(id=89742, name=Blake Simonis)], status=Available)]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at com.sample.api.assertions.PetsAPIAssertions.assertCreatePetResponse(PetsAPIAssertions.java:38)
at com.sample.api.tests.PetsTests.createPetsTest(PetsTests.java:152)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- createPetsTest -->
  <system-out/>
  <testcase classname="com.sample.api.tests.PetsTests" name="getPetsByStatusTest" time="4.143"/>
  <system-out/>
</testsuite> <!-- com.sample.api.tests.PetsTests -->
